# Generated by Django 5.2 on 2025-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Напишите заголовок публикации", max_length=255, verbose_name="Заголовок"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Напишите статью для публикации", verbose_name="Содержимое публикации"),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте изображение",
                        null=True,
                        upload_to="blog/previews_images/",
                        verbose_name="Превью (изображение)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
                ("views_count", models.PositiveIntegerField(default=0, verbose_name="Всего просмотров")),
            ],
            options={
                "verbose_name": "Публикация блога",
                "verbose_name_plural": "Публикации блога",
                "ordering": ["-created_at"],
            },
        ),
    ]
