# Generated by Django 5.2 on 2025-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Введите имя", max_length=150, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(
                        default="example@example.com", help_text="Введите почту", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Введите телефон", max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактная информация",
            },
        ),
    ]
