# Generated by Django 5.2 on 2025-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contactinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2, help_text="Укажите цену закупки", max_digits=10, verbose_name="Цена закупки"
            ),
        ),
    ]
